runtime: nodejs18

entrypoint: node backend/server.js

env_variables:
  NODE_ENV: 'production'
  MONGO_URI: "mongodb+srv://juliey12:dtlPRaYpILjhfozk@vsdproject.mpaaajh.mongodb.net/Node-API?retryWrites=true&w=majority&appName=VSDProject"
  GOOGLE_CLIENT_ID: "1085439417248-q595p4kuj6prlp6tqnrj371kn7vaust7.apps.googleusercontent.com"

handlers:
- url: /api/.*
  script: auto
  secure: always

- url: /(.*\.(json|ico|js|css|png|jpg|svg))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|css|png|jpg|svg)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
