version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://rmahesh7:tarotcards@rmahesh15.shoterg.mongodb.net/TarotCardsVSD?retryWrites=true&w=majority&appName=rmahesh15
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
